### ISSUE TITLE
Trigger stop event 

### ISSUE THREAD

**Issue by BoyZeePoole** [hootsuite/grid#101]
Hi, I'm writing unit tests and would like to trigger the stop event in my test code.

**Comment by andrei-picus-hs** [comment]
You mean the drag stop event? Since the event handler is [attached](https://github.com/hootsuite/grid/blob/ee255749482aab8d47d5a2a33a65323d4d8c963c/src/jquery.gridList.js#L128) using jQuery's `on()` method, you can use [`jQuery.trigger`](http://devdocs.io/jquery/trigger) to trigger it. You could also write Selenium tests that control an actual browser.

P.S.: these wouldn't be unit tests as you're checking both the jQuery plugin and the underlying lib.
